# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libssl1.0.0
env:
  - NOT_CRAN=true

after_success:
    - Rscript -e 'covr::codecov()'
